#############################################################################
# Makefile for building: GPSBabel
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  GPSBabel.pro
# Template: app
# Command: /opt/local/libexec/qt5-mac/bin/qmake -spec macx-xcode -o GPSBabel.xcodeproj/project.pbxproj GPSBabel.pro
#############################################################################

MAKEFILE      = project.pbxproj

QMAKE    = /opt/local/libexec/qt5-mac/bin/qmake
GPSBabel.xcodeproj/project.pbxproj: GPSBabel.pro /opt/local/libexec/qt5-mac/mkspecs/macx-clang/qmake.conf /opt/local/libexec/qt5-mac/mkspecs/features/spec_pre.prf \
		/opt/local/libexec/qt5-mac/mkspecs/qdevice.pri \
		/opt/local/libexec/qt5-mac/mkspecs/features/device_config.prf \
		/opt/local/libexec/qt5-mac/mkspecs/common/shell-unix.conf \
		/opt/local/libexec/qt5-mac/mkspecs/common/unix.conf \
		/opt/local/libexec/qt5-mac/mkspecs/common/mac.conf \
		/opt/local/libexec/qt5-mac/mkspecs/common/macx.conf \
		/opt/local/libexec/qt5-mac/mkspecs/common/gcc-base.conf \
		/opt/local/libexec/qt5-mac/mkspecs/common/gcc-base-mac.conf \
		/opt/local/libexec/qt5-mac/mkspecs/common/clang.conf \
		/opt/local/libexec/qt5-mac/mkspecs/common/clang-mac.conf \
		/opt/local/libexec/qt5-mac/mkspecs/qconfig.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_core.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_core_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_declarative.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_designer.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_gui.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_help.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_help_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_macextras.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_macextras_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_network.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_network_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_nfc.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_opengl.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_positioning.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_qml.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_quick.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_script.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_script_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_sensors.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_serialport.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_sql.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_svg.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_testlib.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_uitools.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_webkit.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_widgets.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_xml.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/local/libexec/qt5-mac/mkspecs/features/qt_functions.prf \
		/opt/local/libexec/qt5-mac/mkspecs/features/qt_config.prf \
		/opt/local/libexec/qt5-mac/mkspecs/macx-clang/qmake.conf \
		/opt/local/libexec/qt5-mac/mkspecs/macx-xcode/qmake.conf \
		/opt/local/libexec/qt5-mac/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/local/libexec/qt5-mac/mkspecs/features/exclusive_builds.prf \
		/opt/local/libexec/qt5-mac/mkspecs/features/default_pre.prf \
		/opt/local/libexec/qt5-mac/mkspecs/features/mac/default_pre.prf \
		/opt/local/libexec/qt5-mac/mkspecs/features/resolve_config.prf \
		/opt/local/libexec/qt5-mac/mkspecs/features/default_post.prf \
		/opt/local/libexec/qt5-mac/mkspecs/features/mac/sdk.prf \
		/opt/local/libexec/qt5-mac/mkspecs/features/mac/default_post.prf \
		/opt/local/libexec/qt5-mac/mkspecs/features/mac/objective_c.prf \
		/opt/local/libexec/qt5-mac/mkspecs/features/warn_on.prf \
		/opt/local/libexec/qt5-mac/mkspecs/features/qt.prf \
		/opt/local/libexec/qt5-mac/mkspecs/features/resources.prf \
		/opt/local/libexec/qt5-mac/mkspecs/features/moc.prf \
		/opt/local/libexec/qt5-mac/mkspecs/features/unix/thread.prf \
		/opt/local/libexec/qt5-mac/mkspecs/features/mac/rez.prf \
		/opt/local/libexec/qt5-mac/mkspecs/features/testcase_targets.prf \
		/opt/local/libexec/qt5-mac/mkspecs/features/exceptions.prf \
		/opt/local/libexec/qt5-mac/mkspecs/features/yacc.prf \
		/opt/local/libexec/qt5-mac/mkspecs/features/lex.prf \
		GPSBabel.pro \
		/opt/local/libexec/qt5-mac/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-xcode -o GPSBabel.xcodeproj/project.pbxproj GPSBabel.pro
/opt/local/libexec/qt5-mac/mkspecs/features/spec_pre.prf:
/opt/local/libexec/qt5-mac/mkspecs/qdevice.pri:
/opt/local/libexec/qt5-mac/mkspecs/features/device_config.prf:
/opt/local/libexec/qt5-mac/mkspecs/common/shell-unix.conf:
/opt/local/libexec/qt5-mac/mkspecs/common/unix.conf:
/opt/local/libexec/qt5-mac/mkspecs/common/mac.conf:
/opt/local/libexec/qt5-mac/mkspecs/common/macx.conf:
/opt/local/libexec/qt5-mac/mkspecs/common/gcc-base.conf:
/opt/local/libexec/qt5-mac/mkspecs/common/gcc-base-mac.conf:
/opt/local/libexec/qt5-mac/mkspecs/common/clang.conf:
/opt/local/libexec/qt5-mac/mkspecs/common/clang-mac.conf:
/opt/local/libexec/qt5-mac/mkspecs/qconfig.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_concurrent.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_core.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_core_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_declarative.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_declarative_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_designer.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_designer_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_gui.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_gui_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_help.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_help_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_macextras.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_macextras_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_multimedia.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_network.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_network_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_nfc.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_opengl.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_positioning.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_printsupport.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_qml.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_qml_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_qmltest.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_quick.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_quick_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_script.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_script_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_scripttools.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_sensors.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_serialport.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_sql.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_sql_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_svg.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_svg_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_testlib.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_uitools.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_webkit.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_webkit_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_webkitwidgets.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_widgets.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_xml.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_xml_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/local/libexec/qt5-mac/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/local/libexec/qt5-mac/mkspecs/features/qt_functions.prf:
/opt/local/libexec/qt5-mac/mkspecs/features/qt_config.prf:
/opt/local/libexec/qt5-mac/mkspecs/macx-clang/qmake.conf:
/opt/local/libexec/qt5-mac/mkspecs/macx-xcode/qmake.conf:
/opt/local/libexec/qt5-mac/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/local/libexec/qt5-mac/mkspecs/features/exclusive_builds.prf:
/opt/local/libexec/qt5-mac/mkspecs/features/default_pre.prf:
/opt/local/libexec/qt5-mac/mkspecs/features/mac/default_pre.prf:
/opt/local/libexec/qt5-mac/mkspecs/features/resolve_config.prf:
/opt/local/libexec/qt5-mac/mkspecs/features/default_post.prf:
/opt/local/libexec/qt5-mac/mkspecs/features/mac/sdk.prf:
/opt/local/libexec/qt5-mac/mkspecs/features/mac/default_post.prf:
/opt/local/libexec/qt5-mac/mkspecs/features/mac/objective_c.prf:
/opt/local/libexec/qt5-mac/mkspecs/features/warn_on.prf:
/opt/local/libexec/qt5-mac/mkspecs/features/qt.prf:
/opt/local/libexec/qt5-mac/mkspecs/features/resources.prf:
/opt/local/libexec/qt5-mac/mkspecs/features/moc.prf:
/opt/local/libexec/qt5-mac/mkspecs/features/unix/thread.prf:
/opt/local/libexec/qt5-mac/mkspecs/features/mac/rez.prf:
/opt/local/libexec/qt5-mac/mkspecs/features/testcase_targets.prf:
/opt/local/libexec/qt5-mac/mkspecs/features/exceptions.prf:
/opt/local/libexec/qt5-mac/mkspecs/features/yacc.prf:
/opt/local/libexec/qt5-mac/mkspecs/features/lex.prf:
GPSBabel.pro:
/opt/local/libexec/qt5-mac/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-xcode -o GPSBabel.xcodeproj/project.pbxproj GPSBabel.pro

qmake_all: FORCE

