#!/bin/sh

#
# delete all files listed in .gitignore
#

find . -type d | 
while read dirname; do
	test -s "$dirname/.gitignore" || continue
	while read filemask; do
		test -z "$filemask" && continue
		cmd="rm -Rfv $dirname/$filemask"
		${cmd}
	done < "$dirname/.gitignore"
done
